# Generated by Django 3.1.4 on 2020-12-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201225_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
