# Generated by Django 3.1.4 on 2020-12-25 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_transaction_variant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='time',
            new_name='timestamp',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(blank=True, max_length=20, null=True)),
                ('buyer_name', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=20)),
                ('observation', models.TextField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.variant')),
            ],
        ),
    ]
