# Generated by Django 3.1.4 on 2020-12-25 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='seller_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
    ]
