# Generated by Django 3.1.4 on 2020-12-25 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20201225_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='seller_name',
            new_name='user',
        ),
    ]
